### ISSUE TITLE
Hardware build instructions & wiring schemes

### ISSUE THREAD

**Issue by cRoCx** [raidlman/1d-pong#3]
I was fascinated by the game as I was playing it at the HTWK Leipzig a while back and would like to build this project, too. But I'm a beginner in hardware. Would it be possible to publish the instuctions?

**Comment by raidlman** [comment]
I've added a schematic for the wiring in the latest commit. Do you need more details? I took some pictures while assembling everything. If you want I can upload and share them as well.

**Comment by cRoCx** [comment]
Thank you. That helped me indeed getting all the hardware, after a few weeks on research here and there and a lot of reading and getting into the topic. I took a different Arduino board, since the Arduino Pro Mini seems outdated now. I've got an error during compilation now, which I will describe in another issue which also seems unrelated to the hardware.

**Comment by cRoCx** [comment]
I failed using a different Arduino board as mentioned in #4. Additionally I've also tried Adafruit's Trinket M0 and Gemma M0 without success, despite the Gemma M0 having too few pins anyway.

But Adafruit is still producing Arduino Pro Minis and, hell yeah, with integrated USB support, so no Serial-to-USB-Adapter needed, except for attaching the serial monitor. So I took an Adafruit Pro Mini 5V 16MHz now!

I've tried to not use the resistor first, since I had none at hand and I wanted to connect fewer cables and pins together than in the wiring scheme. Instead I tried connecting the buttons to the board pins and ground directly. Most Arduino boards like this allow this using the instruction `pinMode(pin, INPUT_PULLUP);` instead of `pinMode(pin, INPUT);`.
The ArduinoIDE has a good example for this accessible in the menu File -> Examples -> Digital -> DigitalInputPullup or see here [arduino.cc InputPullupSerial](https://www.arduino.cc/en/Tutorial/BuiltInExamples/InputPullupSerial).

I tried adapting this into the Button.cpp here
https://github.com/raidlman/1d-pong/blob/7a03ea0de621e74a311400ab0a429472601f9a95/Button.cpp#L42
and here
https://github.com/raidlman/1d-pong/blob/7a03ea0de621e74a311400ab0a429472601f9a95/Button.cpp#L32
but it didn't work somehow.

So I had to give the resistor a try and build a resistor using paper and pencil [like shown in this YouTube tutorial](https://www.youtube.com/watch?v=A2uDVQEUMIM) and it works now. I will of course soon buy real resistors.

It is btw. not neccessary to use 10k Ohms. I've tested it successfully with 2k Ohms as well. A higher resistance than 10k Ohms might work, too.

**Comment by cRoCx** [comment]
This commit here is quite useful in my opinion: "First game start after registration after some seconds. No more reset required." -> https://github.com/KarFreitag/1d-pong/commit/479bc8e9b530d8d80adaa3076adfddccdf8d461a

Additionally I have implemented this commit including my comment into my local copy https://github.com/KarFreitag/1d-pong/commit/479bc8e9b530d8d80adaa3076adfddccdf8d461a#r47669883. That renders the separate reset button obsolete. I guess it's up to personal preference whether to use a separate reset button and/or having the screensaver functionality and/or using the reset button directly on the Arduino board.
